### ISSUE TITLE
The regex ".snmpTrapAddress.0 ([\d.+]+)" seems to create a traceback in some instances

### ISSUE THREAD

**Issue by tfidecki** [OpensourceICTSolutions/zabbix-snmp-traps-script#3]
Oct 26 12:06:56 ems2012 snmptrapd[116233]: 2020-10-26 12:06:56 <UNKNOWN> [UDP: [10.3.4.115]:39465->[10.7.5.66]:162]:#012DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (22912) 0:03:49.12#011SNMPv2-MIB::snmpTrapOID.0 = OID: TITAN-Alarm-MIB::titanAlarmNotification#011TITAN-Alarm-MIB::titanAlarmTimestamp = STRING: 2020-10-26,8:7:4.3,-4:0#011TITAN-Alarm-MIB::titanAlarmSeverity = INTEGER: clear(1)#011TITAN-Alarm-MIB::titanAlarmSubsystem = STRING: accounting#011TITAN-Alarm-MIB::titanAlarmId = INTEGER: 60#011TITAN-Alarm-MIB::titanAlarmResource = STRING: test#011TITAN-Alarm-MIB::titanAlarmProbableCause = STRING: RSA key file path 'TEST' cannot be found for remote host 'TEST'.#011TITAN-Alarm-MIB::titanAlarmAdditionalText = STRING: #011TITAN-Alarm-MIB::titanAlarmRepairAction = STRING: Verify that the RSA file path provided for the tdr rsa-key-file transfer is valid.
Oct 26 12:06:56 ems2012 snmptrapd[116233]: Traceback (most recent call last):
Oct 26 12:06:56 ems2012 snmptrapd[116233]:  File "/usr/bin/snmptrap-parser.py", line 39, in <module>
Oct 26 12:06:56 ems2012 snmptrapd[116233]:    main()
Oct 26 12:06:56 ems2012 snmptrapd[116233]:  File "/usr/bin/snmptrap-parser.py", line 28, in main
Oct 26 12:06:56 ems2012 snmptrapd[116233]:    source = re.findall(".snmpTrapAddress.0 ([\d.+]+)", r)[0]
Oct 26 12:06:56 ems2012 snmptrapd[116233]: IndexError: list index out of range

**Comment by larcorba** [comment]
Hi @tfidecki,

What seems to be your issue?

**Comment by larcorba** [comment]
No reply for several months. Issue closed

**Comment by szuro** [comment]
I encountered the exact same problem, so I'd love to see this issue reopened.

To reproduce:
On a fresh VM (in my case Ubuntu 20.04 or CentOS8) follow the [instructions](https://blog.zabbix.com/parsing-snmp-traps-with-python-or-bash-a-net-snmp-perl-alternative/11577/) for snmptraps
Send a single trap: `snmptrap -v 1 -c public 127.0.0.1 '.1.3.6.1.6.3.1.1.5.4' '0.0.0.0' 6 33 '55' .1.3.6.1.6.3.1.1.5.4 s "eth0"`
In snmptrapd logs you will find the following traceback (log header omited):
```
Traceback (most recent call last):
    File "/usr/bin/snmptrap-parser.py", line 60, in <module>
    main()
  File "/usr/bin/snmptrap-parser.py", line 49, in main
    source = re.findall(".snmpTrapAddress.0 ([\d.+]+)", r)[0]
IndexError: list index out of range
```

The fix is rather simple (and crude). Just simplify the regex from `".snmpTrapAddress.0 ([\d.+]+)` to `"([\d.+]+)`.

If you believe the regex is correct, but the VM needs additional configuration I'd be happy with an updated instruction.

**Comment by larcorba** [comment]
Hi Robert,

Thanks for the additional information and proposed solution. Please allow me some time to do some testing and see if I can reproduce the issue myself. I'll update you once I know the results.

**Comment by larcorba** [comment]
New version of the script uploaded, should work again :) Changed it to make sure trap IP addresses are matched correctly now.

Thanks for letting us know!
